using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TableTool
{
    static class Constants
    {
        public const string ConfigFile = "config.json";
        public const string UserConfig = "user.json";
        public const string SortAndBuild = "SortAndBuild";
        public const string KeysField = "Keys";
        public const string ItemsField = "Items";
        public const string CopyrightComment = "Auto generated by TableTool, copyright PokGame@2014";
    }
}
